export const GUESS_LETTER = 'GAME/GUESS_LETTER';
export const LETTER_GUESSED = 'GAME/LETTER_GUESSED';
export const LETTER_MISSED = 'GAME/LETTER_MISSED';

export const GAME_OVER = 'GAME/GAME_OVER';
export const GAME_RESTART = 'GAME/GAME_RESTART';